In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,2,6,7,8])
print(arr)

[1 3 2 6 7 8]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr_2d = np.array([[1,2,3],[5,6,7]])
print(arr_2d)
print(arr_2d.ndim)
print(type(arr_2d))

[[1 2 3]
 [5 6 7]]
2
<class 'numpy.ndarray'>


In [6]:
arr_3d = np.array([[[1,2,3],1,3,5],[5,6,7],[6,7,8]]])
print(arr_3d)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2074700730.py, line 1)

In [ ]:
arr_3d = np.array([[1,3,2],[5,5,5],
                   [[1,2,3],]]])

In [10]:
arr = np.array([1,2,3,4], ndim = 5)
print(arr)

TypeError: array() got an unexpected keyword argument 'ndim'

In [11]:
print(arr_2d[1])

[5 6 7]


In [13]:
a = np.array([1,2,3,5,6])
print([2])

[2]


In [16]:
a = np.array([[1,2,3],[5,6,7]])
print(a.ndim)
print(a[0,2])

2
3


In [18]:
arr_2d.dtype

dtype('int64')

In [21]:
sarr = np.array([1,2,3,5],dtype="S")
print(sarr)
sarr.dtype

[b'1' b'2' b'3' b'5']


dtype('S1')

In [22]:
newiarr = sarr.astype("I")

In [23]:
newiarr.dtype

dtype('uint32')

In [31]:
sarr = sarr.astype(float)

In [30]:
sarr.dtype

dtype('float64')

In [32]:
sarr = sarr.astype(bool)

In [33]:
print(sarr)

[ True  True  True  True]


In [35]:
sarr.astype('int')

array([1, 1, 1, 1])

In [38]:
sarr = np.array([1,2,3,5])

In [39]:
sarr

array([1, 2, 3, 5])

In [40]:
c = sarr.copy()

In [41]:
c

array([1, 2, 3, 5])

In [42]:
sarr[0] = 13

In [44]:
sarr

array([13,  2,  3,  5])

In [45]:
v = sarr.view()

In [46]:
sarr[0] = 55
print(v)

[55  2  3  5]


In [49]:
v.base

array([55,  2,  3,  5])

In [50]:
v.copy

<function ndarray.copy>

In [51]:
fived = np.array([1,2,5,6],ndmin=5)
fived

array([[[[[1, 2, 5, 6]]]]])

In [52]:
fived.shape

(1, 1, 1, 1, 4)